service: snow-alert

provider:
  name: aws
  runtime: nodejs18.x

functions:
  dataBaseHandler:
    handler: registerForAlerts.handler
    events:
      - httpApi:
          path: /
          method: post
  cronHandler:
    handler: makeAlerts.handler
    events:
      - schedule: rate(1 hour)
      - schedule: cron(40 16 * * ? *)
