service: snow-alert

provider:
  name: aws
  runtime: nodejs18.x

functions:
  registerForAlerts:
    handler: registerForAlerts.handler
    events:
      - httpApi:
          path: /
          method: post
  makeAlerts:
    handler: makeAlerts.handler
    events:
      - schedule: rate(1 hour)
